export const ERROR_CODES = Object.freeze({
  APP_VERSION_UNSUPPORTED: 'APP_VERSION_UNSUPPORTED',
  PROFILE_INCOMPATIBLE: 'PROFILE_INCOMPATIBLE',
  SCHEMA_DRIFT: 'SCHEMA_DRIFT',
  LOGIN_LOST: 'LOGIN_LOST',
  RISK_CONTROL: 'RISK_CONTROL',
  RATE_LIMITED: 'RATE_LIMITED',
  FRIDA_DISCONNECTED: 'FRIDA_DISCONNECTED',
  EMULATOR_UNAVAILABLE: 'EMULATOR_UNAVAILABLE'
});

export const GLOBAL_BLOCKER_CODES = Object.freeze(new Set(Object.values(ERROR_CODES)));
